name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  cucumber_test:
    runs-on: ruby:3.3.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Set up deps
      - name: Install Dependencies
        run: |
          bundle install
          bundle exec rails db:migrate

      # Step 2: Test
      - name: Run Cucumber Tests
        id: cucumber
        run: |
          output=$(bundle exec cucumber | tee /dev/tty)
          report_url=$(echo "$output" | grep -oP 'View your Cucumber Report at: \K.*')
          echo "report_url=$report_url" >> $GITHUB_ENV

      # Step 3: Artifact
      - name: Download Cucumber Report
        run: |
          curl -o cucumber_report.html "$report_url"
        env:
          report_url: ${{ env.report_url }}

      - name: Upload Cucumber Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: cucumber_report.html